-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sssp_kernel_0_PE_kernel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_in_a_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    local_in_a_ce0 : OUT STD_LOGIC;
    local_in_a_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_in_a_offset : IN STD_LOGIC_VECTOR (6 downto 0);
    local_in_b_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    local_in_b_ce0 : OUT STD_LOGIC;
    local_in_b_q0 : IN STD_LOGIC_VECTOR (4 downto 0);
    local_in_b_offset : IN STD_LOGIC_VECTOR (6 downto 0);
    local_in_c_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    local_in_c_ce0 : OUT STD_LOGIC;
    local_in_c_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_in_c_offset : IN STD_LOGIC_VECTOR (6 downto 0);
    local_out_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    local_out_ce0 : OUT STD_LOGIC;
    local_out_we0 : OUT STD_LOGIC;
    local_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_out_offset : IN STD_LOGIC_VECTOR (6 downto 0);
    v : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sssp_kernel_0_PE_kernel is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_144_fu_472_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_144_reg_1167 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_142_fu_481_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_142_reg_1173 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_143_fu_490_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_143_reg_1178 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_145_fu_637_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal tmp_145_reg_1279 : STD_LOGIC_VECTOR (36 downto 0);
    signal tmp_s_fu_646_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_reg_1284 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_ap_idle : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_ap_ready : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0 : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_idle : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_ready : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0 : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_ce0 : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_ce0 : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out_ap_vld : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_ap_idle : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_ap_ready : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_ce0 : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_we0 : STD_LOGIC;
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln32_fu_631_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sssp_kernel_0_PE_kernel_Pipeline_init_distances IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln27 : IN STD_LOGIC_VECTOR (11 downto 0);
        local_in_a_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        local_in_a_ce0 : OUT STD_LOGIC;
        local_in_a_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_31_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_31_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_30_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_30_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_29_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_29_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_28_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_28_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_27_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_27_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_26_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_26_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_25_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_25_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_24_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_24_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_23_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_23_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_22_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_22_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_21_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_21_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_20_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_20_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_19_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_19_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_18_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_18_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_17_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_17_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_16_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_16_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_15_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_15_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_14_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_14_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_13_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_13_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_12_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_12_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_11_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_11_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_10_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_10_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_9_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_9_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_8_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_8_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_7_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_7_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_6_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_6_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_5_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_5_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_4_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_4_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_3_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_3_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_2_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_2_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_1_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_1_0_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_0_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_0_0_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sssp_kernel_0_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        distance_buffer_31_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_30_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_29_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_28_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_27_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_26_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_25_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_24_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_23_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_22_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_21_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_20_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_19_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_18_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_17_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_16_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_15_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_14_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_13_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_12_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_11_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_10_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_9_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_8_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_7_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_6_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_5_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_4_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_3_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_2_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_1_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_0_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        bound : IN STD_LOGIC_VECTOR (36 downto 0);
        zext_ln27 : IN STD_LOGIC_VECTOR (11 downto 0);
        local_in_a_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        local_in_a_ce0 : OUT STD_LOGIC;
        local_in_a_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln36 : IN STD_LOGIC_VECTOR (11 downto 0);
        local_in_b_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        local_in_b_ce0 : OUT STD_LOGIC;
        local_in_b_q0 : IN STD_LOGIC_VECTOR (4 downto 0);
        zext_ln37 : IN STD_LOGIC_VECTOR (11 downto 0);
        local_in_c_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        local_in_c_ce0 : OUT STD_LOGIC;
        local_in_c_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_31_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_31_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_30_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_30_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_29_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_29_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_28_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_28_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_27_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_27_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_26_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_26_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_25_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_25_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_24_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_24_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_23_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_23_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_22_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_22_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_21_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_21_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_20_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_20_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_19_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_19_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_18_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_18_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_17_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_17_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_16_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_16_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_15_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_15_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_14_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_14_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_13_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_13_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_12_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_12_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_11_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_11_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_10_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_10_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_9_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_9_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_8_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_8_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_7_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_7_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_6_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_6_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_5_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_5_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_4_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_4_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_3_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_3_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_2_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_2_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_1_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_1_3_out_ap_vld : OUT STD_LOGIC;
        distance_buffer_0_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_0_3_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sssp_kernel_0_PE_kernel_Pipeline_write_distances IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln49 : IN STD_LOGIC_VECTOR (11 downto 0);
        local_out_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        local_out_ce0 : OUT STD_LOGIC;
        local_out_we0 : OUT STD_LOGIC;
        local_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_0_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_1_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_2_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_3_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_4_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_5_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_6_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_7_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_8_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_9_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_10_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_11_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_12_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_13_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_14_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_15_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_16_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_17_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_18_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_19_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_20_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_21_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_22_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_23_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_24_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_25_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_26_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_27_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_28_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_29_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_30_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        distance_buffer_31_3_reload : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_PE_kernel_Pipeline_init_distances_fu_316 : component sssp_kernel_0_PE_kernel_Pipeline_init_distances
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start,
        ap_done => grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done,
        ap_idle => grp_PE_kernel_Pipeline_init_distances_fu_316_ap_idle,
        ap_ready => grp_PE_kernel_Pipeline_init_distances_fu_316_ap_ready,
        zext_ln27 => tmp_144_reg_1167,
        local_in_a_address0 => grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0,
        local_in_a_ce0 => grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0,
        local_in_a_q0 => local_in_a_q0,
        distance_buffer_31_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out,
        distance_buffer_31_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out_ap_vld,
        distance_buffer_30_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out,
        distance_buffer_30_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out_ap_vld,
        distance_buffer_29_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out,
        distance_buffer_29_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out_ap_vld,
        distance_buffer_28_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out,
        distance_buffer_28_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out_ap_vld,
        distance_buffer_27_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out,
        distance_buffer_27_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out_ap_vld,
        distance_buffer_26_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out,
        distance_buffer_26_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out_ap_vld,
        distance_buffer_25_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out,
        distance_buffer_25_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out_ap_vld,
        distance_buffer_24_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out,
        distance_buffer_24_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out_ap_vld,
        distance_buffer_23_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out,
        distance_buffer_23_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out_ap_vld,
        distance_buffer_22_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out,
        distance_buffer_22_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out_ap_vld,
        distance_buffer_21_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out,
        distance_buffer_21_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out_ap_vld,
        distance_buffer_20_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out,
        distance_buffer_20_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out_ap_vld,
        distance_buffer_19_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out,
        distance_buffer_19_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out_ap_vld,
        distance_buffer_18_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out,
        distance_buffer_18_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out_ap_vld,
        distance_buffer_17_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out,
        distance_buffer_17_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out_ap_vld,
        distance_buffer_16_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out,
        distance_buffer_16_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out_ap_vld,
        distance_buffer_15_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out,
        distance_buffer_15_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out_ap_vld,
        distance_buffer_14_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out,
        distance_buffer_14_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out_ap_vld,
        distance_buffer_13_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out,
        distance_buffer_13_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out_ap_vld,
        distance_buffer_12_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out,
        distance_buffer_12_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out_ap_vld,
        distance_buffer_11_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out,
        distance_buffer_11_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out_ap_vld,
        distance_buffer_10_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out,
        distance_buffer_10_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out_ap_vld,
        distance_buffer_9_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out,
        distance_buffer_9_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out_ap_vld,
        distance_buffer_8_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out,
        distance_buffer_8_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out_ap_vld,
        distance_buffer_7_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out,
        distance_buffer_7_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out_ap_vld,
        distance_buffer_6_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out,
        distance_buffer_6_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out_ap_vld,
        distance_buffer_5_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out,
        distance_buffer_5_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out_ap_vld,
        distance_buffer_4_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out,
        distance_buffer_4_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out_ap_vld,
        distance_buffer_3_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out,
        distance_buffer_3_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out_ap_vld,
        distance_buffer_2_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out,
        distance_buffer_2_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out_ap_vld,
        distance_buffer_1_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out,
        distance_buffer_1_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out_ap_vld,
        distance_buffer_0_0_out => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out,
        distance_buffer_0_0_out_ap_vld => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out_ap_vld);

    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355 : component sssp_kernel_0_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start,
        ap_done => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done,
        ap_idle => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_idle,
        ap_ready => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_ready,
        distance_buffer_31_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out,
        distance_buffer_30_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out,
        distance_buffer_29_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out,
        distance_buffer_28_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out,
        distance_buffer_27_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out,
        distance_buffer_26_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out,
        distance_buffer_25_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out,
        distance_buffer_24_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out,
        distance_buffer_23_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out,
        distance_buffer_22_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out,
        distance_buffer_21_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out,
        distance_buffer_20_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out,
        distance_buffer_19_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out,
        distance_buffer_18_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out,
        distance_buffer_17_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out,
        distance_buffer_16_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out,
        distance_buffer_15_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out,
        distance_buffer_14_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out,
        distance_buffer_13_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out,
        distance_buffer_12_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out,
        distance_buffer_11_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out,
        distance_buffer_10_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out,
        distance_buffer_9_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out,
        distance_buffer_8_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out,
        distance_buffer_7_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out,
        distance_buffer_6_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out,
        distance_buffer_5_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out,
        distance_buffer_4_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out,
        distance_buffer_3_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out,
        distance_buffer_2_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out,
        distance_buffer_1_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out,
        distance_buffer_0_0_reload => grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out,
        bound => tmp_145_reg_1279,
        zext_ln27 => tmp_144_reg_1167,
        local_in_a_address0 => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0,
        local_in_a_ce0 => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0,
        local_in_a_q0 => local_in_a_q0,
        zext_ln36 => tmp_143_reg_1178,
        local_in_b_address0 => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_address0,
        local_in_b_ce0 => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_ce0,
        local_in_b_q0 => local_in_b_q0,
        zext_ln37 => tmp_142_reg_1173,
        local_in_c_address0 => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_address0,
        local_in_c_ce0 => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_ce0,
        local_in_c_q0 => local_in_c_q0,
        distance_buffer_31_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out,
        distance_buffer_31_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out_ap_vld,
        distance_buffer_30_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out,
        distance_buffer_30_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out_ap_vld,
        distance_buffer_29_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out,
        distance_buffer_29_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out_ap_vld,
        distance_buffer_28_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out,
        distance_buffer_28_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out_ap_vld,
        distance_buffer_27_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out,
        distance_buffer_27_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out_ap_vld,
        distance_buffer_26_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out,
        distance_buffer_26_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out_ap_vld,
        distance_buffer_25_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out,
        distance_buffer_25_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out_ap_vld,
        distance_buffer_24_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out,
        distance_buffer_24_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out_ap_vld,
        distance_buffer_23_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out,
        distance_buffer_23_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out_ap_vld,
        distance_buffer_22_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out,
        distance_buffer_22_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out_ap_vld,
        distance_buffer_21_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out,
        distance_buffer_21_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out_ap_vld,
        distance_buffer_20_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out,
        distance_buffer_20_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out_ap_vld,
        distance_buffer_19_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out,
        distance_buffer_19_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out_ap_vld,
        distance_buffer_18_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out,
        distance_buffer_18_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out_ap_vld,
        distance_buffer_17_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out,
        distance_buffer_17_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out_ap_vld,
        distance_buffer_16_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out,
        distance_buffer_16_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out_ap_vld,
        distance_buffer_15_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out,
        distance_buffer_15_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out_ap_vld,
        distance_buffer_14_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out,
        distance_buffer_14_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out_ap_vld,
        distance_buffer_13_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out,
        distance_buffer_13_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out_ap_vld,
        distance_buffer_12_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out,
        distance_buffer_12_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out_ap_vld,
        distance_buffer_11_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out,
        distance_buffer_11_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out_ap_vld,
        distance_buffer_10_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out,
        distance_buffer_10_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out_ap_vld,
        distance_buffer_9_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out,
        distance_buffer_9_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out_ap_vld,
        distance_buffer_8_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out,
        distance_buffer_8_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out_ap_vld,
        distance_buffer_7_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out,
        distance_buffer_7_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out_ap_vld,
        distance_buffer_6_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out,
        distance_buffer_6_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out_ap_vld,
        distance_buffer_5_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out,
        distance_buffer_5_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out_ap_vld,
        distance_buffer_4_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out,
        distance_buffer_4_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out_ap_vld,
        distance_buffer_3_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out,
        distance_buffer_3_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out_ap_vld,
        distance_buffer_2_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out,
        distance_buffer_2_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out_ap_vld,
        distance_buffer_1_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out,
        distance_buffer_1_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out_ap_vld,
        distance_buffer_0_3_out => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out,
        distance_buffer_0_3_out_ap_vld => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out_ap_vld);

    grp_PE_kernel_Pipeline_write_distances_fu_433 : component sssp_kernel_0_PE_kernel_Pipeline_write_distances
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start,
        ap_done => grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done,
        ap_idle => grp_PE_kernel_Pipeline_write_distances_fu_433_ap_idle,
        ap_ready => grp_PE_kernel_Pipeline_write_distances_fu_433_ap_ready,
        zext_ln49 => tmp_s_reg_1284,
        local_out_address0 => grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_address0,
        local_out_ce0 => grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_ce0,
        local_out_we0 => grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_we0,
        local_out_d0 => grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_d0,
        distance_buffer_0_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out,
        distance_buffer_1_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out,
        distance_buffer_2_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out,
        distance_buffer_3_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out,
        distance_buffer_4_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out,
        distance_buffer_5_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out,
        distance_buffer_6_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out,
        distance_buffer_7_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out,
        distance_buffer_8_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out,
        distance_buffer_9_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out,
        distance_buffer_10_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out,
        distance_buffer_11_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out,
        distance_buffer_12_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out,
        distance_buffer_13_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out,
        distance_buffer_14_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out,
        distance_buffer_15_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out,
        distance_buffer_16_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out,
        distance_buffer_17_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out,
        distance_buffer_18_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out,
        distance_buffer_19_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out,
        distance_buffer_20_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out,
        distance_buffer_21_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out,
        distance_buffer_22_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out,
        distance_buffer_23_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out,
        distance_buffer_24_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out,
        distance_buffer_25_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out,
        distance_buffer_26_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out,
        distance_buffer_27_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out,
        distance_buffer_28_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out,
        distance_buffer_29_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out,
        distance_buffer_30_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out,
        distance_buffer_31_3_reload => grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_PE_kernel_Pipeline_init_distances_fu_316_ap_ready = ap_const_logic_1)) then 
                    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_ready = ap_const_logic_1)) then 
                    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_ready = ap_const_logic_1)) then 
                    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    tmp_142_reg_1173(11 downto 5) <= tmp_142_fu_481_p3(11 downto 5);
                    tmp_143_reg_1178(11 downto 5) <= tmp_143_fu_490_p3(11 downto 5);
                    tmp_145_reg_1279(36 downto 5) <= tmp_145_fu_637_p3(36 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    tmp_144_reg_1167(11 downto 5) <= tmp_144_fu_472_p3(11 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    tmp_s_reg_1284(11 downto 5) <= tmp_s_fu_646_p3(11 downto 5);
            end if;
        end if;
    end process;
    tmp_144_reg_1167(4 downto 0) <= "00000";
    tmp_142_reg_1173(4 downto 0) <= "00000";
    tmp_143_reg_1178(4 downto 0) <= "00000";
    tmp_145_reg_1279(4 downto 0) <= "00000";
    tmp_s_reg_1284(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done, grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done, grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln32_fu_631_p2 <= std_logic_vector(unsigned(v) + unsigned(ap_const_lv32_FFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done)
    begin
        if ((grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done)
    begin
        if ((grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done)
    begin
        if ((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done, ap_CS_fsm_state6)
    begin
        if ((((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start <= grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg;
    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg;
    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start <= grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg;

    local_in_a_address0_assign_proc : process(grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0, grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_in_a_address0 <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            local_in_a_address0 <= grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0;
        else 
            local_in_a_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    local_in_a_ce0_assign_proc : process(grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0, grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_in_a_ce0 <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            local_in_a_ce0 <= grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0;
        else 
            local_in_a_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_in_b_address0 <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_address0;
    local_in_b_ce0 <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_ce0;
    local_in_c_address0 <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_address0;
    local_in_c_ce0 <= grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_ce0;
    local_out_address0 <= grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_address0;
    local_out_ce0 <= grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_ce0;
    local_out_d0 <= grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_d0;
    local_out_we0 <= grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_we0;
    tmp_142_fu_481_p3 <= (local_in_c_offset & ap_const_lv5_0);
    tmp_143_fu_490_p3 <= (local_in_b_offset & ap_const_lv5_0);
    tmp_144_fu_472_p3 <= (local_in_a_offset & ap_const_lv5_0);
    tmp_145_fu_637_p3 <= (add_ln32_fu_631_p2 & ap_const_lv5_0);
    tmp_s_fu_646_p3 <= (local_out_offset & ap_const_lv5_0);
end behav;
