// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sssp_kernel_0_PE_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_in_a_address0,
        local_in_a_ce0,
        local_in_a_q0,
        local_in_a_offset,
        local_in_b_address0,
        local_in_b_ce0,
        local_in_b_q0,
        local_in_b_offset,
        local_in_c_address0,
        local_in_c_ce0,
        local_in_c_q0,
        local_in_c_offset,
        local_out_address0,
        local_out_ce0,
        local_out_we0,
        local_out_d0,
        local_out_offset,
        v
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] local_in_a_address0;
output   local_in_a_ce0;
input  [31:0] local_in_a_q0;
input  [6:0] local_in_a_offset;
output  [11:0] local_in_b_address0;
output   local_in_b_ce0;
input  [4:0] local_in_b_q0;
input  [6:0] local_in_b_offset;
output  [11:0] local_in_c_address0;
output   local_in_c_ce0;
input  [31:0] local_in_c_q0;
input  [6:0] local_in_c_offset;
output  [11:0] local_out_address0;
output   local_out_ce0;
output   local_out_we0;
output  [31:0] local_out_d0;
input  [6:0] local_out_offset;
input  [31:0] v;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] local_in_a_address0;
reg local_in_a_ce0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] tmp_144_fu_472_p3;
reg   [11:0] tmp_144_reg_1167;
wire   [11:0] tmp_142_fu_481_p3;
reg   [11:0] tmp_142_reg_1173;
wire    ap_CS_fsm_state3;
wire   [11:0] tmp_143_fu_490_p3;
reg   [11:0] tmp_143_reg_1178;
wire   [36:0] tmp_145_fu_637_p3;
reg   [36:0] tmp_145_reg_1279;
wire   [11:0] tmp_s_fu_646_p3;
reg   [11:0] tmp_s_reg_1284;
wire    ap_CS_fsm_state5;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_idle;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_ready;
wire   [11:0] grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out;
wire    grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out_ap_vld;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_idle;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_ready;
wire   [11:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0;
wire   [11:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_address0;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_ce0;
wire   [11:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_address0;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_ce0;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out_ap_vld;
wire   [31:0] grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out;
wire    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out_ap_vld;
wire    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start;
wire    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done;
wire    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_idle;
wire    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_ready;
wire   [11:0] grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_address0;
wire    grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_ce0;
wire    grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_we0;
wire   [31:0] grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_d0;
reg    grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln32_fu_631_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg = 1'b0;
#0 grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg = 1'b0;
#0 grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg = 1'b0;
end

sssp_kernel_0_PE_kernel_Pipeline_init_distances grp_PE_kernel_Pipeline_init_distances_fu_316(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start),
    .ap_done(grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done),
    .ap_idle(grp_PE_kernel_Pipeline_init_distances_fu_316_ap_idle),
    .ap_ready(grp_PE_kernel_Pipeline_init_distances_fu_316_ap_ready),
    .zext_ln27(tmp_144_reg_1167),
    .local_in_a_address0(grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0),
    .local_in_a_ce0(grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0),
    .local_in_a_q0(local_in_a_q0),
    .distance_buffer_31_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out),
    .distance_buffer_31_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out_ap_vld),
    .distance_buffer_30_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out),
    .distance_buffer_30_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out_ap_vld),
    .distance_buffer_29_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out),
    .distance_buffer_29_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out_ap_vld),
    .distance_buffer_28_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out),
    .distance_buffer_28_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out_ap_vld),
    .distance_buffer_27_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out),
    .distance_buffer_27_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out_ap_vld),
    .distance_buffer_26_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out),
    .distance_buffer_26_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out_ap_vld),
    .distance_buffer_25_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out),
    .distance_buffer_25_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out_ap_vld),
    .distance_buffer_24_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out),
    .distance_buffer_24_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out_ap_vld),
    .distance_buffer_23_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out),
    .distance_buffer_23_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out_ap_vld),
    .distance_buffer_22_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out),
    .distance_buffer_22_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out_ap_vld),
    .distance_buffer_21_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out),
    .distance_buffer_21_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out_ap_vld),
    .distance_buffer_20_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out),
    .distance_buffer_20_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out_ap_vld),
    .distance_buffer_19_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out),
    .distance_buffer_19_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out_ap_vld),
    .distance_buffer_18_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out),
    .distance_buffer_18_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out_ap_vld),
    .distance_buffer_17_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out),
    .distance_buffer_17_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out_ap_vld),
    .distance_buffer_16_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out),
    .distance_buffer_16_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out_ap_vld),
    .distance_buffer_15_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out),
    .distance_buffer_15_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out_ap_vld),
    .distance_buffer_14_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out),
    .distance_buffer_14_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out_ap_vld),
    .distance_buffer_13_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out),
    .distance_buffer_13_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out_ap_vld),
    .distance_buffer_12_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out),
    .distance_buffer_12_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out_ap_vld),
    .distance_buffer_11_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out),
    .distance_buffer_11_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out_ap_vld),
    .distance_buffer_10_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out),
    .distance_buffer_10_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out_ap_vld),
    .distance_buffer_9_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out),
    .distance_buffer_9_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out_ap_vld),
    .distance_buffer_8_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out),
    .distance_buffer_8_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out_ap_vld),
    .distance_buffer_7_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out),
    .distance_buffer_7_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out_ap_vld),
    .distance_buffer_6_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out),
    .distance_buffer_6_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out_ap_vld),
    .distance_buffer_5_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out),
    .distance_buffer_5_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out_ap_vld),
    .distance_buffer_4_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out),
    .distance_buffer_4_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out_ap_vld),
    .distance_buffer_3_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out),
    .distance_buffer_3_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out_ap_vld),
    .distance_buffer_2_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out),
    .distance_buffer_2_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out_ap_vld),
    .distance_buffer_1_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out),
    .distance_buffer_1_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out_ap_vld),
    .distance_buffer_0_0_out(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out),
    .distance_buffer_0_0_out_ap_vld(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out_ap_vld)
);

sssp_kernel_0_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1 grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start),
    .ap_done(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done),
    .ap_idle(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_idle),
    .ap_ready(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_ready),
    .distance_buffer_31_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_31_0_out),
    .distance_buffer_30_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_30_0_out),
    .distance_buffer_29_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_29_0_out),
    .distance_buffer_28_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_28_0_out),
    .distance_buffer_27_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_27_0_out),
    .distance_buffer_26_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_26_0_out),
    .distance_buffer_25_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_25_0_out),
    .distance_buffer_24_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_24_0_out),
    .distance_buffer_23_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_23_0_out),
    .distance_buffer_22_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_22_0_out),
    .distance_buffer_21_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_21_0_out),
    .distance_buffer_20_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_20_0_out),
    .distance_buffer_19_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_19_0_out),
    .distance_buffer_18_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_18_0_out),
    .distance_buffer_17_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_17_0_out),
    .distance_buffer_16_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_16_0_out),
    .distance_buffer_15_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_15_0_out),
    .distance_buffer_14_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_14_0_out),
    .distance_buffer_13_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_13_0_out),
    .distance_buffer_12_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_12_0_out),
    .distance_buffer_11_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_11_0_out),
    .distance_buffer_10_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_10_0_out),
    .distance_buffer_9_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_9_0_out),
    .distance_buffer_8_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_8_0_out),
    .distance_buffer_7_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_7_0_out),
    .distance_buffer_6_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_6_0_out),
    .distance_buffer_5_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_5_0_out),
    .distance_buffer_4_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_4_0_out),
    .distance_buffer_3_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_3_0_out),
    .distance_buffer_2_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_2_0_out),
    .distance_buffer_1_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_1_0_out),
    .distance_buffer_0_0_reload(grp_PE_kernel_Pipeline_init_distances_fu_316_distance_buffer_0_0_out),
    .bound(tmp_145_reg_1279),
    .zext_ln27(tmp_144_reg_1167),
    .local_in_a_address0(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0),
    .local_in_a_ce0(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0),
    .local_in_a_q0(local_in_a_q0),
    .zext_ln36(tmp_143_reg_1178),
    .local_in_b_address0(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_address0),
    .local_in_b_ce0(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_ce0),
    .local_in_b_q0(local_in_b_q0),
    .zext_ln37(tmp_142_reg_1173),
    .local_in_c_address0(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_address0),
    .local_in_c_ce0(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_ce0),
    .local_in_c_q0(local_in_c_q0),
    .distance_buffer_31_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out),
    .distance_buffer_31_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out_ap_vld),
    .distance_buffer_30_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out),
    .distance_buffer_30_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out_ap_vld),
    .distance_buffer_29_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out),
    .distance_buffer_29_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out_ap_vld),
    .distance_buffer_28_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out),
    .distance_buffer_28_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out_ap_vld),
    .distance_buffer_27_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out),
    .distance_buffer_27_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out_ap_vld),
    .distance_buffer_26_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out),
    .distance_buffer_26_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out_ap_vld),
    .distance_buffer_25_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out),
    .distance_buffer_25_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out_ap_vld),
    .distance_buffer_24_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out),
    .distance_buffer_24_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out_ap_vld),
    .distance_buffer_23_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out),
    .distance_buffer_23_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out_ap_vld),
    .distance_buffer_22_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out),
    .distance_buffer_22_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out_ap_vld),
    .distance_buffer_21_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out),
    .distance_buffer_21_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out_ap_vld),
    .distance_buffer_20_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out),
    .distance_buffer_20_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out_ap_vld),
    .distance_buffer_19_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out),
    .distance_buffer_19_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out_ap_vld),
    .distance_buffer_18_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out),
    .distance_buffer_18_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out_ap_vld),
    .distance_buffer_17_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out),
    .distance_buffer_17_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out_ap_vld),
    .distance_buffer_16_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out),
    .distance_buffer_16_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out_ap_vld),
    .distance_buffer_15_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out),
    .distance_buffer_15_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out_ap_vld),
    .distance_buffer_14_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out),
    .distance_buffer_14_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out_ap_vld),
    .distance_buffer_13_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out),
    .distance_buffer_13_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out_ap_vld),
    .distance_buffer_12_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out),
    .distance_buffer_12_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out_ap_vld),
    .distance_buffer_11_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out),
    .distance_buffer_11_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out_ap_vld),
    .distance_buffer_10_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out),
    .distance_buffer_10_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out_ap_vld),
    .distance_buffer_9_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out),
    .distance_buffer_9_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out_ap_vld),
    .distance_buffer_8_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out),
    .distance_buffer_8_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out_ap_vld),
    .distance_buffer_7_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out),
    .distance_buffer_7_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out_ap_vld),
    .distance_buffer_6_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out),
    .distance_buffer_6_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out_ap_vld),
    .distance_buffer_5_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out),
    .distance_buffer_5_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out_ap_vld),
    .distance_buffer_4_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out),
    .distance_buffer_4_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out_ap_vld),
    .distance_buffer_3_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out),
    .distance_buffer_3_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out_ap_vld),
    .distance_buffer_2_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out),
    .distance_buffer_2_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out_ap_vld),
    .distance_buffer_1_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out),
    .distance_buffer_1_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out_ap_vld),
    .distance_buffer_0_3_out(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out),
    .distance_buffer_0_3_out_ap_vld(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out_ap_vld)
);

sssp_kernel_0_PE_kernel_Pipeline_write_distances grp_PE_kernel_Pipeline_write_distances_fu_433(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start),
    .ap_done(grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done),
    .ap_idle(grp_PE_kernel_Pipeline_write_distances_fu_433_ap_idle),
    .ap_ready(grp_PE_kernel_Pipeline_write_distances_fu_433_ap_ready),
    .zext_ln49(tmp_s_reg_1284),
    .local_out_address0(grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_address0),
    .local_out_ce0(grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_ce0),
    .local_out_we0(grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_we0),
    .local_out_d0(grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_d0),
    .distance_buffer_0_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_0_3_out),
    .distance_buffer_1_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_1_3_out),
    .distance_buffer_2_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_2_3_out),
    .distance_buffer_3_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_3_3_out),
    .distance_buffer_4_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_4_3_out),
    .distance_buffer_5_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_5_3_out),
    .distance_buffer_6_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_6_3_out),
    .distance_buffer_7_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_7_3_out),
    .distance_buffer_8_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_8_3_out),
    .distance_buffer_9_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_9_3_out),
    .distance_buffer_10_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_10_3_out),
    .distance_buffer_11_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_11_3_out),
    .distance_buffer_12_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_12_3_out),
    .distance_buffer_13_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_13_3_out),
    .distance_buffer_14_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_14_3_out),
    .distance_buffer_15_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_15_3_out),
    .distance_buffer_16_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_16_3_out),
    .distance_buffer_17_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_17_3_out),
    .distance_buffer_18_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_18_3_out),
    .distance_buffer_19_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_19_3_out),
    .distance_buffer_20_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_20_3_out),
    .distance_buffer_21_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_21_3_out),
    .distance_buffer_22_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_22_3_out),
    .distance_buffer_23_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_23_3_out),
    .distance_buffer_24_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_24_3_out),
    .distance_buffer_25_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_25_3_out),
    .distance_buffer_26_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_26_3_out),
    .distance_buffer_27_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_27_3_out),
    .distance_buffer_28_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_28_3_out),
    .distance_buffer_29_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_29_3_out),
    .distance_buffer_30_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_30_3_out),
    .distance_buffer_31_3_reload(grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_distance_buffer_31_3_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg <= 1'b1;
        end else if ((grp_PE_kernel_Pipeline_init_distances_fu_316_ap_ready == 1'b1)) begin
            grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg <= 1'b1;
        end else if ((grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_ready == 1'b1)) begin
            grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg <= 1'b1;
        end else if ((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_ready == 1'b1)) begin
            grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_142_reg_1173[11 : 5] <= tmp_142_fu_481_p3[11 : 5];
        tmp_143_reg_1178[11 : 5] <= tmp_143_fu_490_p3[11 : 5];
        tmp_145_reg_1279[36 : 5] <= tmp_145_fu_637_p3[36 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_144_reg_1167[11 : 5] <= tmp_144_fu_472_p3[11 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_s_reg_1284[11 : 5] <= tmp_s_fu_646_p3[11 : 5];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_in_a_address0 = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_a_address0 = grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_address0;
    end else begin
        local_in_a_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_in_a_ce0 = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_a_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_in_a_ce0 = grp_PE_kernel_Pipeline_init_distances_fu_316_local_in_a_ce0;
    end else begin
        local_in_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_PE_kernel_Pipeline_init_distances_fu_316_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_PE_kernel_Pipeline_write_distances_fu_433_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_631_p2 = ($signed(v) + $signed(32'd4294967295));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start = grp_PE_kernel_Pipeline_init_distances_fu_316_ap_start_reg;

assign grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_ap_start_reg;

assign grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start = grp_PE_kernel_Pipeline_write_distances_fu_433_ap_start_reg;

assign local_in_b_address0 = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_address0;

assign local_in_b_ce0 = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_b_ce0;

assign local_in_c_address0 = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_address0;

assign local_in_c_ce0 = grp_PE_kernel_Pipeline_sssp_computation_VITIS_LOOP_33_1_fu_355_local_in_c_ce0;

assign local_out_address0 = grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_address0;

assign local_out_ce0 = grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_ce0;

assign local_out_d0 = grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_d0;

assign local_out_we0 = grp_PE_kernel_Pipeline_write_distances_fu_433_local_out_we0;

assign tmp_142_fu_481_p3 = {{local_in_c_offset}, {5'd0}};

assign tmp_143_fu_490_p3 = {{local_in_b_offset}, {5'd0}};

assign tmp_144_fu_472_p3 = {{local_in_a_offset}, {5'd0}};

assign tmp_145_fu_637_p3 = {{add_ln32_fu_631_p2}, {5'd0}};

assign tmp_s_fu_646_p3 = {{local_out_offset}, {5'd0}};

always @ (posedge ap_clk) begin
    tmp_144_reg_1167[4:0] <= 5'b00000;
    tmp_142_reg_1173[4:0] <= 5'b00000;
    tmp_143_reg_1178[4:0] <= 5'b00000;
    tmp_145_reg_1279[4:0] <= 5'b00000;
    tmp_s_reg_1284[4:0] <= 5'b00000;
end

endmodule //sssp_kernel_0_PE_kernel
