// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sssp_kernel_0_PE_kernel_1_Pipeline_sssp_computation_VITIS_LOOP_33_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        distance_buffer_31_0_reload,
        distance_buffer_30_0_reload,
        distance_buffer_29_0_reload,
        distance_buffer_28_0_reload,
        distance_buffer_27_0_reload,
        distance_buffer_26_0_reload,
        distance_buffer_25_0_reload,
        distance_buffer_24_0_reload,
        distance_buffer_23_0_reload,
        distance_buffer_22_0_reload,
        distance_buffer_21_0_reload,
        distance_buffer_20_0_reload,
        distance_buffer_19_0_reload,
        distance_buffer_18_0_reload,
        distance_buffer_17_0_reload,
        distance_buffer_16_0_reload,
        distance_buffer_15_0_reload,
        distance_buffer_14_0_reload,
        distance_buffer_13_0_reload,
        distance_buffer_12_0_reload,
        distance_buffer_11_0_reload,
        distance_buffer_10_0_reload,
        distance_buffer_9_0_reload,
        distance_buffer_8_0_reload,
        distance_buffer_7_0_reload,
        distance_buffer_6_0_reload,
        distance_buffer_5_0_reload,
        distance_buffer_4_0_reload,
        distance_buffer_3_0_reload,
        distance_buffer_2_0_reload,
        distance_buffer_1_0_reload,
        distance_buffer_0_0_reload,
        bound,
        zext_ln27,
        local_in_a_address0,
        local_in_a_ce0,
        local_in_a_q0,
        zext_ln36,
        local_in_b_address0,
        local_in_b_ce0,
        local_in_b_q0,
        zext_ln37,
        local_in_c_address0,
        local_in_c_ce0,
        local_in_c_q0,
        distance_buffer_31_3_out,
        distance_buffer_31_3_out_ap_vld,
        distance_buffer_30_3_out,
        distance_buffer_30_3_out_ap_vld,
        distance_buffer_29_3_out,
        distance_buffer_29_3_out_ap_vld,
        distance_buffer_28_3_out,
        distance_buffer_28_3_out_ap_vld,
        distance_buffer_27_3_out,
        distance_buffer_27_3_out_ap_vld,
        distance_buffer_26_3_out,
        distance_buffer_26_3_out_ap_vld,
        distance_buffer_25_3_out,
        distance_buffer_25_3_out_ap_vld,
        distance_buffer_24_3_out,
        distance_buffer_24_3_out_ap_vld,
        distance_buffer_23_3_out,
        distance_buffer_23_3_out_ap_vld,
        distance_buffer_22_3_out,
        distance_buffer_22_3_out_ap_vld,
        distance_buffer_21_3_out,
        distance_buffer_21_3_out_ap_vld,
        distance_buffer_20_3_out,
        distance_buffer_20_3_out_ap_vld,
        distance_buffer_19_3_out,
        distance_buffer_19_3_out_ap_vld,
        distance_buffer_18_3_out,
        distance_buffer_18_3_out_ap_vld,
        distance_buffer_17_3_out,
        distance_buffer_17_3_out_ap_vld,
        distance_buffer_16_3_out,
        distance_buffer_16_3_out_ap_vld,
        distance_buffer_15_3_out,
        distance_buffer_15_3_out_ap_vld,
        distance_buffer_14_3_out,
        distance_buffer_14_3_out_ap_vld,
        distance_buffer_13_3_out,
        distance_buffer_13_3_out_ap_vld,
        distance_buffer_12_3_out,
        distance_buffer_12_3_out_ap_vld,
        distance_buffer_11_3_out,
        distance_buffer_11_3_out_ap_vld,
        distance_buffer_10_3_out,
        distance_buffer_10_3_out_ap_vld,
        distance_buffer_9_3_out,
        distance_buffer_9_3_out_ap_vld,
        distance_buffer_8_3_out,
        distance_buffer_8_3_out_ap_vld,
        distance_buffer_7_3_out,
        distance_buffer_7_3_out_ap_vld,
        distance_buffer_6_3_out,
        distance_buffer_6_3_out_ap_vld,
        distance_buffer_5_3_out,
        distance_buffer_5_3_out_ap_vld,
        distance_buffer_4_3_out,
        distance_buffer_4_3_out_ap_vld,
        distance_buffer_3_3_out,
        distance_buffer_3_3_out_ap_vld,
        distance_buffer_2_3_out,
        distance_buffer_2_3_out_ap_vld,
        distance_buffer_1_3_out,
        distance_buffer_1_3_out_ap_vld,
        distance_buffer_0_31_out,
        distance_buffer_0_31_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] distance_buffer_31_0_reload;
input  [31:0] distance_buffer_30_0_reload;
input  [31:0] distance_buffer_29_0_reload;
input  [31:0] distance_buffer_28_0_reload;
input  [31:0] distance_buffer_27_0_reload;
input  [31:0] distance_buffer_26_0_reload;
input  [31:0] distance_buffer_25_0_reload;
input  [31:0] distance_buffer_24_0_reload;
input  [31:0] distance_buffer_23_0_reload;
input  [31:0] distance_buffer_22_0_reload;
input  [31:0] distance_buffer_21_0_reload;
input  [31:0] distance_buffer_20_0_reload;
input  [31:0] distance_buffer_19_0_reload;
input  [31:0] distance_buffer_18_0_reload;
input  [31:0] distance_buffer_17_0_reload;
input  [31:0] distance_buffer_16_0_reload;
input  [31:0] distance_buffer_15_0_reload;
input  [31:0] distance_buffer_14_0_reload;
input  [31:0] distance_buffer_13_0_reload;
input  [31:0] distance_buffer_12_0_reload;
input  [31:0] distance_buffer_11_0_reload;
input  [31:0] distance_buffer_10_0_reload;
input  [31:0] distance_buffer_9_0_reload;
input  [31:0] distance_buffer_8_0_reload;
input  [31:0] distance_buffer_7_0_reload;
input  [31:0] distance_buffer_6_0_reload;
input  [31:0] distance_buffer_5_0_reload;
input  [31:0] distance_buffer_4_0_reload;
input  [31:0] distance_buffer_3_0_reload;
input  [31:0] distance_buffer_2_0_reload;
input  [31:0] distance_buffer_1_0_reload;
input  [31:0] distance_buffer_0_0_reload;
input  [36:0] bound;
input  [11:0] zext_ln27;
output  [11:0] local_in_a_address0;
output   local_in_a_ce0;
input  [31:0] local_in_a_q0;
input  [11:0] zext_ln36;
output  [11:0] local_in_b_address0;
output   local_in_b_ce0;
input  [4:0] local_in_b_q0;
input  [11:0] zext_ln37;
output  [11:0] local_in_c_address0;
output   local_in_c_ce0;
input  [31:0] local_in_c_q0;
output  [31:0] distance_buffer_31_3_out;
output   distance_buffer_31_3_out_ap_vld;
output  [31:0] distance_buffer_30_3_out;
output   distance_buffer_30_3_out_ap_vld;
output  [31:0] distance_buffer_29_3_out;
output   distance_buffer_29_3_out_ap_vld;
output  [31:0] distance_buffer_28_3_out;
output   distance_buffer_28_3_out_ap_vld;
output  [31:0] distance_buffer_27_3_out;
output   distance_buffer_27_3_out_ap_vld;
output  [31:0] distance_buffer_26_3_out;
output   distance_buffer_26_3_out_ap_vld;
output  [31:0] distance_buffer_25_3_out;
output   distance_buffer_25_3_out_ap_vld;
output  [31:0] distance_buffer_24_3_out;
output   distance_buffer_24_3_out_ap_vld;
output  [31:0] distance_buffer_23_3_out;
output   distance_buffer_23_3_out_ap_vld;
output  [31:0] distance_buffer_22_3_out;
output   distance_buffer_22_3_out_ap_vld;
output  [31:0] distance_buffer_21_3_out;
output   distance_buffer_21_3_out_ap_vld;
output  [31:0] distance_buffer_20_3_out;
output   distance_buffer_20_3_out_ap_vld;
output  [31:0] distance_buffer_19_3_out;
output   distance_buffer_19_3_out_ap_vld;
output  [31:0] distance_buffer_18_3_out;
output   distance_buffer_18_3_out_ap_vld;
output  [31:0] distance_buffer_17_3_out;
output   distance_buffer_17_3_out_ap_vld;
output  [31:0] distance_buffer_16_3_out;
output   distance_buffer_16_3_out_ap_vld;
output  [31:0] distance_buffer_15_3_out;
output   distance_buffer_15_3_out_ap_vld;
output  [31:0] distance_buffer_14_3_out;
output   distance_buffer_14_3_out_ap_vld;
output  [31:0] distance_buffer_13_3_out;
output   distance_buffer_13_3_out_ap_vld;
output  [31:0] distance_buffer_12_3_out;
output   distance_buffer_12_3_out_ap_vld;
output  [31:0] distance_buffer_11_3_out;
output   distance_buffer_11_3_out_ap_vld;
output  [31:0] distance_buffer_10_3_out;
output   distance_buffer_10_3_out_ap_vld;
output  [31:0] distance_buffer_9_3_out;
output   distance_buffer_9_3_out_ap_vld;
output  [31:0] distance_buffer_8_3_out;
output   distance_buffer_8_3_out_ap_vld;
output  [31:0] distance_buffer_7_3_out;
output   distance_buffer_7_3_out_ap_vld;
output  [31:0] distance_buffer_6_3_out;
output   distance_buffer_6_3_out_ap_vld;
output  [31:0] distance_buffer_5_3_out;
output   distance_buffer_5_3_out_ap_vld;
output  [31:0] distance_buffer_4_3_out;
output   distance_buffer_4_3_out_ap_vld;
output  [31:0] distance_buffer_3_3_out;
output   distance_buffer_3_3_out_ap_vld;
output  [31:0] distance_buffer_2_3_out;
output   distance_buffer_2_3_out_ap_vld;
output  [31:0] distance_buffer_1_3_out;
output   distance_buffer_1_3_out_ap_vld;
output  [31:0] distance_buffer_0_31_out;
output   distance_buffer_0_31_out_ap_vld;

reg ap_idle;
reg local_in_a_ce0;
reg local_in_b_ce0;
reg local_in_c_ce0;
reg distance_buffer_31_3_out_ap_vld;
reg distance_buffer_30_3_out_ap_vld;
reg distance_buffer_29_3_out_ap_vld;
reg distance_buffer_28_3_out_ap_vld;
reg distance_buffer_27_3_out_ap_vld;
reg distance_buffer_26_3_out_ap_vld;
reg distance_buffer_25_3_out_ap_vld;
reg distance_buffer_24_3_out_ap_vld;
reg distance_buffer_23_3_out_ap_vld;
reg distance_buffer_22_3_out_ap_vld;
reg distance_buffer_21_3_out_ap_vld;
reg distance_buffer_20_3_out_ap_vld;
reg distance_buffer_19_3_out_ap_vld;
reg distance_buffer_18_3_out_ap_vld;
reg distance_buffer_17_3_out_ap_vld;
reg distance_buffer_16_3_out_ap_vld;
reg distance_buffer_15_3_out_ap_vld;
reg distance_buffer_14_3_out_ap_vld;
reg distance_buffer_13_3_out_ap_vld;
reg distance_buffer_12_3_out_ap_vld;
reg distance_buffer_11_3_out_ap_vld;
reg distance_buffer_10_3_out_ap_vld;
reg distance_buffer_9_3_out_ap_vld;
reg distance_buffer_8_3_out_ap_vld;
reg distance_buffer_7_3_out_ap_vld;
reg distance_buffer_6_3_out_ap_vld;
reg distance_buffer_5_3_out_ap_vld;
reg distance_buffer_4_3_out_ap_vld;
reg distance_buffer_3_3_out_ap_vld;
reg distance_buffer_2_3_out_ap_vld;
reg distance_buffer_1_3_out_ap_vld;
reg distance_buffer_0_31_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_1030_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln32_reg_1907;
reg   [0:0] icmp_ln32_reg_1907_pp0_iter2_reg;
wire   [5:0] select_ln32_fu_1050_p3;
reg   [5:0] select_ln32_reg_1911;
reg   [31:0] distance_buffer_1_load_2_reg_1931;
reg   [31:0] distance_buffer_1_3_load101_reg_1936;
reg   [31:0] distance_buffer_1_34_load_1_reg_1941;
reg   [31:0] distance_buffer_1_35_load_1_reg_1946;
reg   [31:0] distance_buffer_1_36_load_1_reg_1951;
reg   [31:0] distance_buffer_1_37_load_1_reg_1956;
reg   [31:0] distance_buffer_1_38_load_1_reg_1961;
reg   [31:0] distance_buffer_1_39_load_1_reg_1966;
reg   [31:0] distance_buffer_1_40_load_1_reg_1971;
reg   [31:0] distance_buffer_1_41_load_1_reg_1976;
reg   [31:0] distance_buffer_1_42_load_1_reg_1981;
reg   [31:0] distance_buffer_1_43_load_1_reg_1986;
reg   [31:0] distance_buffer_1_44_load_1_reg_1991;
reg   [31:0] distance_buffer_1_45_load_1_reg_1996;
reg   [31:0] distance_buffer_1_46_load_1_reg_2001;
reg   [31:0] distance_buffer_1_47_load_1_reg_2006;
reg   [31:0] distance_buffer_1_48_load_1_reg_2011;
reg   [31:0] distance_buffer_1_49_load_1_reg_2016;
reg   [31:0] distance_buffer_1_50_load_1_reg_2021;
reg   [31:0] distance_buffer_1_51_load_1_reg_2026;
reg   [31:0] distance_buffer_1_52_load_1_reg_2031;
reg   [31:0] distance_buffer_1_53_load_1_reg_2036;
reg   [31:0] distance_buffer_1_54_load_1_reg_2041;
reg   [31:0] distance_buffer_1_55_load_1_reg_2046;
reg   [31:0] distance_buffer_1_56_load_1_reg_2051;
reg   [31:0] distance_buffer_1_57_load_1_reg_2056;
reg   [31:0] distance_buffer_1_58_load_1_reg_2061;
reg   [31:0] distance_buffer_1_59_load_1_reg_2066;
reg   [31:0] distance_buffer_1_60_load_1_reg_2071;
reg   [31:0] distance_buffer_1_61_load_1_reg_2076;
reg   [31:0] distance_buffer_1_62_load_1_reg_2081;
reg   [31:0] distance_buffer_1_63_load_1_reg_2086;
reg   [4:0] dst_reg_2091;
reg   [31:0] weight_reg_2096;
wire   [31:0] tmp_fu_1207_p34;
reg   [31:0] tmp_reg_2101;
wire   [63:0] zext_ln35_2_fu_1082_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln36_2_fu_1092_p1;
wire   [63:0] zext_ln37_2_fu_1102_p1;
reg   [5:0] j_1_fu_242;
wire   [5:0] add_ln33_fu_1058_p2;
wire    ap_loop_init;
reg   [36:0] indvar_flatten_fu_246;
wire   [36:0] add_ln32_fu_1035_p2;
reg   [31:0] distance_buffer_1_fu_250;
wire   [31:0] distance_buffer_1_65_fu_1282_p2;
wire   [0:0] icmp_ln39_fu_1277_p2;
wire   [0:0] icmp_ln39_1_fu_1323_p2;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_load_2;
reg   [31:0] distance_buffer_1_3_fu_254;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_3_load101;
reg   [31:0] distance_buffer_1_34_fu_258;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_34_load_1;
reg   [31:0] distance_buffer_1_35_fu_262;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_35_load_1;
reg   [31:0] distance_buffer_1_36_fu_266;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_36_load_1;
reg   [31:0] distance_buffer_1_37_fu_270;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_37_load_1;
reg   [31:0] distance_buffer_1_38_fu_274;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_38_load_1;
reg   [31:0] distance_buffer_1_39_fu_278;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_39_load_1;
reg   [31:0] distance_buffer_1_40_fu_282;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_40_load_1;
reg   [31:0] distance_buffer_1_41_fu_286;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_41_load_1;
reg   [31:0] distance_buffer_1_42_fu_290;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_42_load_1;
reg   [31:0] distance_buffer_1_43_fu_294;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_43_load_1;
reg   [31:0] distance_buffer_1_44_fu_298;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_44_load_1;
reg   [31:0] distance_buffer_1_45_fu_302;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_45_load_1;
reg   [31:0] distance_buffer_1_46_fu_306;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_46_load_1;
reg   [31:0] distance_buffer_1_47_fu_310;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_47_load_1;
reg   [31:0] distance_buffer_1_48_fu_314;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_48_load_1;
reg   [31:0] distance_buffer_1_49_fu_318;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_49_load_1;
reg   [31:0] distance_buffer_1_50_fu_322;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_50_load_1;
reg   [31:0] distance_buffer_1_51_fu_326;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_51_load_1;
reg   [31:0] distance_buffer_1_52_fu_330;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_52_load_1;
reg   [31:0] distance_buffer_1_53_fu_334;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_53_load_1;
reg   [31:0] distance_buffer_1_54_fu_338;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_54_load_1;
reg   [31:0] distance_buffer_1_55_fu_342;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_55_load_1;
reg   [31:0] distance_buffer_1_56_fu_346;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_56_load_1;
reg   [31:0] distance_buffer_1_57_fu_350;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_57_load_1;
reg   [31:0] distance_buffer_1_58_fu_354;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_58_load_1;
reg   [31:0] distance_buffer_1_59_fu_358;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_59_load_1;
reg   [31:0] distance_buffer_1_60_fu_362;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_60_load_1;
reg   [31:0] distance_buffer_1_61_fu_366;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_61_load_1;
reg   [31:0] distance_buffer_1_62_fu_370;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_62_load_1;
reg   [31:0] distance_buffer_1_63_fu_374;
reg   [31:0] ap_sig_allocacmp_distance_buffer_1_63_load_1;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln33_fu_1044_p2;
wire   [11:0] zext_ln35_fu_1074_p1;
wire   [11:0] add_ln35_fu_1077_p2;
wire   [11:0] add_ln36_fu_1087_p2;
wire   [11:0] add_ln37_fu_1097_p2;
wire   [4:0] tmp_fu_1207_p33;
wire   [31:0] tmp_s_fu_1286_p34;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1000;
reg    ap_condition_1003;
reg    ap_condition_1006;
reg    ap_condition_1009;
reg    ap_condition_1012;
reg    ap_condition_1015;
reg    ap_condition_1018;
reg    ap_condition_1021;
reg    ap_condition_1024;
reg    ap_condition_1027;
reg    ap_condition_1030;
reg    ap_condition_1033;
reg    ap_condition_1036;
reg    ap_condition_1039;
reg    ap_condition_1042;
reg    ap_condition_1045;
reg    ap_condition_1048;
reg    ap_condition_1051;
reg    ap_condition_1054;
reg    ap_condition_1057;
reg    ap_condition_1060;
reg    ap_condition_1063;
reg    ap_condition_1066;
reg    ap_condition_1069;
reg    ap_condition_1072;
reg    ap_condition_1075;
reg    ap_condition_1078;
reg    ap_condition_1081;
reg    ap_condition_1084;
reg    ap_condition_1087;
reg    ap_condition_1090;
reg    ap_condition_1093;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

sssp_kernel_0_mux_325_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_325_32_1_1_U91(
    .din0(ap_sig_allocacmp_distance_buffer_1_load_2),
    .din1(ap_sig_allocacmp_distance_buffer_1_3_load101),
    .din2(ap_sig_allocacmp_distance_buffer_1_34_load_1),
    .din3(ap_sig_allocacmp_distance_buffer_1_35_load_1),
    .din4(ap_sig_allocacmp_distance_buffer_1_36_load_1),
    .din5(ap_sig_allocacmp_distance_buffer_1_37_load_1),
    .din6(ap_sig_allocacmp_distance_buffer_1_38_load_1),
    .din7(ap_sig_allocacmp_distance_buffer_1_39_load_1),
    .din8(ap_sig_allocacmp_distance_buffer_1_40_load_1),
    .din9(ap_sig_allocacmp_distance_buffer_1_41_load_1),
    .din10(ap_sig_allocacmp_distance_buffer_1_42_load_1),
    .din11(ap_sig_allocacmp_distance_buffer_1_43_load_1),
    .din12(ap_sig_allocacmp_distance_buffer_1_44_load_1),
    .din13(ap_sig_allocacmp_distance_buffer_1_45_load_1),
    .din14(ap_sig_allocacmp_distance_buffer_1_46_load_1),
    .din15(ap_sig_allocacmp_distance_buffer_1_47_load_1),
    .din16(ap_sig_allocacmp_distance_buffer_1_48_load_1),
    .din17(ap_sig_allocacmp_distance_buffer_1_49_load_1),
    .din18(ap_sig_allocacmp_distance_buffer_1_50_load_1),
    .din19(ap_sig_allocacmp_distance_buffer_1_51_load_1),
    .din20(ap_sig_allocacmp_distance_buffer_1_52_load_1),
    .din21(ap_sig_allocacmp_distance_buffer_1_53_load_1),
    .din22(ap_sig_allocacmp_distance_buffer_1_54_load_1),
    .din23(ap_sig_allocacmp_distance_buffer_1_55_load_1),
    .din24(ap_sig_allocacmp_distance_buffer_1_56_load_1),
    .din25(ap_sig_allocacmp_distance_buffer_1_57_load_1),
    .din26(ap_sig_allocacmp_distance_buffer_1_58_load_1),
    .din27(ap_sig_allocacmp_distance_buffer_1_59_load_1),
    .din28(ap_sig_allocacmp_distance_buffer_1_60_load_1),
    .din29(ap_sig_allocacmp_distance_buffer_1_61_load_1),
    .din30(ap_sig_allocacmp_distance_buffer_1_62_load_1),
    .din31(ap_sig_allocacmp_distance_buffer_1_63_load_1),
    .din32(tmp_fu_1207_p33),
    .dout(tmp_fu_1207_p34)
);

sssp_kernel_0_mux_325_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_325_32_1_1_U92(
    .din0(distance_buffer_1_load_2_reg_1931),
    .din1(distance_buffer_1_3_load101_reg_1936),
    .din2(distance_buffer_1_34_load_1_reg_1941),
    .din3(distance_buffer_1_35_load_1_reg_1946),
    .din4(distance_buffer_1_36_load_1_reg_1951),
    .din5(distance_buffer_1_37_load_1_reg_1956),
    .din6(distance_buffer_1_38_load_1_reg_1961),
    .din7(distance_buffer_1_39_load_1_reg_1966),
    .din8(distance_buffer_1_40_load_1_reg_1971),
    .din9(distance_buffer_1_41_load_1_reg_1976),
    .din10(distance_buffer_1_42_load_1_reg_1981),
    .din11(distance_buffer_1_43_load_1_reg_1986),
    .din12(distance_buffer_1_44_load_1_reg_1991),
    .din13(distance_buffer_1_45_load_1_reg_1996),
    .din14(distance_buffer_1_46_load_1_reg_2001),
    .din15(distance_buffer_1_47_load_1_reg_2006),
    .din16(distance_buffer_1_48_load_1_reg_2011),
    .din17(distance_buffer_1_49_load_1_reg_2016),
    .din18(distance_buffer_1_50_load_1_reg_2021),
    .din19(distance_buffer_1_51_load_1_reg_2026),
    .din20(distance_buffer_1_52_load_1_reg_2031),
    .din21(distance_buffer_1_53_load_1_reg_2036),
    .din22(distance_buffer_1_54_load_1_reg_2041),
    .din23(distance_buffer_1_55_load_1_reg_2046),
    .din24(distance_buffer_1_56_load_1_reg_2051),
    .din25(distance_buffer_1_57_load_1_reg_2056),
    .din26(distance_buffer_1_58_load_1_reg_2061),
    .din27(distance_buffer_1_59_load_1_reg_2066),
    .din28(distance_buffer_1_60_load_1_reg_2071),
    .din29(distance_buffer_1_61_load_1_reg_2076),
    .din30(distance_buffer_1_62_load_1_reg_2081),
    .din31(distance_buffer_1_63_load_1_reg_2086),
    .din32(dst_reg_2091),
    .dout(tmp_s_fu_1286_p34)
);

sssp_kernel_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_34_fu_258 <= distance_buffer_2_0_reload;
        end else if ((1'b1 == ap_condition_1000)) begin
            distance_buffer_1_34_fu_258 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_35_fu_262 <= distance_buffer_3_0_reload;
        end else if ((1'b1 == ap_condition_1003)) begin
            distance_buffer_1_35_fu_262 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_36_fu_266 <= distance_buffer_4_0_reload;
        end else if ((1'b1 == ap_condition_1006)) begin
            distance_buffer_1_36_fu_266 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_37_fu_270 <= distance_buffer_5_0_reload;
        end else if ((1'b1 == ap_condition_1009)) begin
            distance_buffer_1_37_fu_270 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_38_fu_274 <= distance_buffer_6_0_reload;
        end else if ((1'b1 == ap_condition_1012)) begin
            distance_buffer_1_38_fu_274 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_39_fu_278 <= distance_buffer_7_0_reload;
        end else if ((1'b1 == ap_condition_1015)) begin
            distance_buffer_1_39_fu_278 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_3_fu_254 <= distance_buffer_1_0_reload;
        end else if ((1'b1 == ap_condition_1018)) begin
            distance_buffer_1_3_fu_254 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_40_fu_282 <= distance_buffer_8_0_reload;
        end else if ((1'b1 == ap_condition_1021)) begin
            distance_buffer_1_40_fu_282 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_41_fu_286 <= distance_buffer_9_0_reload;
        end else if ((1'b1 == ap_condition_1024)) begin
            distance_buffer_1_41_fu_286 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_42_fu_290 <= distance_buffer_10_0_reload;
        end else if ((1'b1 == ap_condition_1027)) begin
            distance_buffer_1_42_fu_290 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_43_fu_294 <= distance_buffer_11_0_reload;
        end else if ((1'b1 == ap_condition_1030)) begin
            distance_buffer_1_43_fu_294 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_44_fu_298 <= distance_buffer_12_0_reload;
        end else if ((1'b1 == ap_condition_1033)) begin
            distance_buffer_1_44_fu_298 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_45_fu_302 <= distance_buffer_13_0_reload;
        end else if ((1'b1 == ap_condition_1036)) begin
            distance_buffer_1_45_fu_302 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_46_fu_306 <= distance_buffer_14_0_reload;
        end else if ((1'b1 == ap_condition_1039)) begin
            distance_buffer_1_46_fu_306 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_47_fu_310 <= distance_buffer_15_0_reload;
        end else if ((1'b1 == ap_condition_1042)) begin
            distance_buffer_1_47_fu_310 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_48_fu_314 <= distance_buffer_16_0_reload;
        end else if ((1'b1 == ap_condition_1045)) begin
            distance_buffer_1_48_fu_314 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_49_fu_318 <= distance_buffer_17_0_reload;
        end else if ((1'b1 == ap_condition_1048)) begin
            distance_buffer_1_49_fu_318 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_50_fu_322 <= distance_buffer_18_0_reload;
        end else if ((1'b1 == ap_condition_1051)) begin
            distance_buffer_1_50_fu_322 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_51_fu_326 <= distance_buffer_19_0_reload;
        end else if ((1'b1 == ap_condition_1054)) begin
            distance_buffer_1_51_fu_326 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_52_fu_330 <= distance_buffer_20_0_reload;
        end else if ((1'b1 == ap_condition_1057)) begin
            distance_buffer_1_52_fu_330 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_53_fu_334 <= distance_buffer_21_0_reload;
        end else if ((1'b1 == ap_condition_1060)) begin
            distance_buffer_1_53_fu_334 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_54_fu_338 <= distance_buffer_22_0_reload;
        end else if ((1'b1 == ap_condition_1063)) begin
            distance_buffer_1_54_fu_338 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_55_fu_342 <= distance_buffer_23_0_reload;
        end else if ((1'b1 == ap_condition_1066)) begin
            distance_buffer_1_55_fu_342 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_56_fu_346 <= distance_buffer_24_0_reload;
        end else if ((1'b1 == ap_condition_1069)) begin
            distance_buffer_1_56_fu_346 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_57_fu_350 <= distance_buffer_25_0_reload;
        end else if ((1'b1 == ap_condition_1072)) begin
            distance_buffer_1_57_fu_350 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_58_fu_354 <= distance_buffer_26_0_reload;
        end else if ((1'b1 == ap_condition_1075)) begin
            distance_buffer_1_58_fu_354 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_59_fu_358 <= distance_buffer_27_0_reload;
        end else if ((1'b1 == ap_condition_1078)) begin
            distance_buffer_1_59_fu_358 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_60_fu_362 <= distance_buffer_28_0_reload;
        end else if ((1'b1 == ap_condition_1081)) begin
            distance_buffer_1_60_fu_362 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_61_fu_366 <= distance_buffer_29_0_reload;
        end else if ((1'b1 == ap_condition_1084)) begin
            distance_buffer_1_61_fu_366 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_62_fu_370 <= distance_buffer_30_0_reload;
        end else if ((1'b1 == ap_condition_1087)) begin
            distance_buffer_1_62_fu_370 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_63_fu_374 <= distance_buffer_31_0_reload;
        end else if ((1'b1 == ap_condition_1090)) begin
            distance_buffer_1_63_fu_374 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            distance_buffer_1_fu_250 <= distance_buffer_0_0_reload;
        end else if ((1'b1 == ap_condition_1093)) begin
            distance_buffer_1_fu_250 <= distance_buffer_1_65_fu_1282_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_246 <= 37'd0;
        end else if (((icmp_ln32_fu_1030_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_246 <= add_ln32_fu_1035_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_1_fu_242 <= 6'd0;
        end else if (((icmp_ln32_fu_1030_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_1_fu_242 <= add_ln33_fu_1058_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln32_reg_1907 <= icmp_ln32_fu_1030_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        distance_buffer_1_34_load_1_reg_1941 <= ap_sig_allocacmp_distance_buffer_1_34_load_1;
        distance_buffer_1_35_load_1_reg_1946 <= ap_sig_allocacmp_distance_buffer_1_35_load_1;
        distance_buffer_1_36_load_1_reg_1951 <= ap_sig_allocacmp_distance_buffer_1_36_load_1;
        distance_buffer_1_37_load_1_reg_1956 <= ap_sig_allocacmp_distance_buffer_1_37_load_1;
        distance_buffer_1_38_load_1_reg_1961 <= ap_sig_allocacmp_distance_buffer_1_38_load_1;
        distance_buffer_1_39_load_1_reg_1966 <= ap_sig_allocacmp_distance_buffer_1_39_load_1;
        distance_buffer_1_3_load101_reg_1936 <= ap_sig_allocacmp_distance_buffer_1_3_load101;
        distance_buffer_1_40_load_1_reg_1971 <= ap_sig_allocacmp_distance_buffer_1_40_load_1;
        distance_buffer_1_41_load_1_reg_1976 <= ap_sig_allocacmp_distance_buffer_1_41_load_1;
        distance_buffer_1_42_load_1_reg_1981 <= ap_sig_allocacmp_distance_buffer_1_42_load_1;
        distance_buffer_1_43_load_1_reg_1986 <= ap_sig_allocacmp_distance_buffer_1_43_load_1;
        distance_buffer_1_44_load_1_reg_1991 <= ap_sig_allocacmp_distance_buffer_1_44_load_1;
        distance_buffer_1_45_load_1_reg_1996 <= ap_sig_allocacmp_distance_buffer_1_45_load_1;
        distance_buffer_1_46_load_1_reg_2001 <= ap_sig_allocacmp_distance_buffer_1_46_load_1;
        distance_buffer_1_47_load_1_reg_2006 <= ap_sig_allocacmp_distance_buffer_1_47_load_1;
        distance_buffer_1_48_load_1_reg_2011 <= ap_sig_allocacmp_distance_buffer_1_48_load_1;
        distance_buffer_1_49_load_1_reg_2016 <= ap_sig_allocacmp_distance_buffer_1_49_load_1;
        distance_buffer_1_50_load_1_reg_2021 <= ap_sig_allocacmp_distance_buffer_1_50_load_1;
        distance_buffer_1_51_load_1_reg_2026 <= ap_sig_allocacmp_distance_buffer_1_51_load_1;
        distance_buffer_1_52_load_1_reg_2031 <= ap_sig_allocacmp_distance_buffer_1_52_load_1;
        distance_buffer_1_53_load_1_reg_2036 <= ap_sig_allocacmp_distance_buffer_1_53_load_1;
        distance_buffer_1_54_load_1_reg_2041 <= ap_sig_allocacmp_distance_buffer_1_54_load_1;
        distance_buffer_1_55_load_1_reg_2046 <= ap_sig_allocacmp_distance_buffer_1_55_load_1;
        distance_buffer_1_56_load_1_reg_2051 <= ap_sig_allocacmp_distance_buffer_1_56_load_1;
        distance_buffer_1_57_load_1_reg_2056 <= ap_sig_allocacmp_distance_buffer_1_57_load_1;
        distance_buffer_1_58_load_1_reg_2061 <= ap_sig_allocacmp_distance_buffer_1_58_load_1;
        distance_buffer_1_59_load_1_reg_2066 <= ap_sig_allocacmp_distance_buffer_1_59_load_1;
        distance_buffer_1_60_load_1_reg_2071 <= ap_sig_allocacmp_distance_buffer_1_60_load_1;
        distance_buffer_1_61_load_1_reg_2076 <= ap_sig_allocacmp_distance_buffer_1_61_load_1;
        distance_buffer_1_62_load_1_reg_2081 <= ap_sig_allocacmp_distance_buffer_1_62_load_1;
        distance_buffer_1_63_load_1_reg_2086 <= ap_sig_allocacmp_distance_buffer_1_63_load_1;
        distance_buffer_1_load_2_reg_1931 <= ap_sig_allocacmp_distance_buffer_1_load_2;
        dst_reg_2091 <= local_in_b_q0;
        icmp_ln32_reg_1907_pp0_iter2_reg <= icmp_ln32_reg_1907;
        tmp_reg_2101 <= tmp_fu_1207_p34;
        weight_reg_2096 <= local_in_c_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_fu_1030_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln32_reg_1911 <= select_ln32_fu_1050_p3;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_1030_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd2) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_34_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_34_load_1 = distance_buffer_1_34_fu_258;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd3) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_35_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_35_load_1 = distance_buffer_1_35_fu_262;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd4) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_36_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_36_load_1 = distance_buffer_1_36_fu_266;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd5) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_37_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_37_load_1 = distance_buffer_1_37_fu_270;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd6) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_38_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_38_load_1 = distance_buffer_1_38_fu_274;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd7) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_39_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_39_load_1 = distance_buffer_1_39_fu_278;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_3_load101 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_3_load101 = distance_buffer_1_3_fu_254;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd8) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_40_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_40_load_1 = distance_buffer_1_40_fu_282;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd9) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_41_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_41_load_1 = distance_buffer_1_41_fu_286;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd10) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_42_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_42_load_1 = distance_buffer_1_42_fu_290;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd11) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_43_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_43_load_1 = distance_buffer_1_43_fu_294;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd12) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_44_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_44_load_1 = distance_buffer_1_44_fu_298;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd13) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_45_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_45_load_1 = distance_buffer_1_45_fu_302;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd14) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_46_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_46_load_1 = distance_buffer_1_46_fu_306;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd15) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_47_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_47_load_1 = distance_buffer_1_47_fu_310;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd16) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_48_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_48_load_1 = distance_buffer_1_48_fu_314;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd17) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_49_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_49_load_1 = distance_buffer_1_49_fu_318;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd18) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_50_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_50_load_1 = distance_buffer_1_50_fu_322;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd19) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_51_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_51_load_1 = distance_buffer_1_51_fu_326;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd20) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_52_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_52_load_1 = distance_buffer_1_52_fu_330;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd21) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_53_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_53_load_1 = distance_buffer_1_53_fu_334;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd22) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_54_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_54_load_1 = distance_buffer_1_54_fu_338;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd23) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_55_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_55_load_1 = distance_buffer_1_55_fu_342;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd24) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_56_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_56_load_1 = distance_buffer_1_56_fu_346;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd25) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_57_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_57_load_1 = distance_buffer_1_57_fu_350;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd26) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_58_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_58_load_1 = distance_buffer_1_58_fu_354;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd27) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_59_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_59_load_1 = distance_buffer_1_59_fu_358;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd28) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_60_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_60_load_1 = distance_buffer_1_60_fu_362;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd29) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_61_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_61_load_1 = distance_buffer_1_61_fu_366;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd30) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_62_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_62_load_1 = distance_buffer_1_62_fu_370;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd31) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_63_load_1 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_63_load_1 = distance_buffer_1_63_fu_374;
    end
end

always @ (*) begin
    if (((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (dst_reg_2091 == 5'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_distance_buffer_1_load_2 = distance_buffer_1_65_fu_1282_p2;
    end else begin
        ap_sig_allocacmp_distance_buffer_1_load_2 = distance_buffer_1_fu_250;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_0_31_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_0_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_10_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_10_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_11_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_11_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_12_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_12_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_13_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_13_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_14_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_14_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_15_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_15_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_16_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_16_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_17_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_17_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_18_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_18_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_19_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_19_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_1_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_1_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_20_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_20_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_21_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_21_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_22_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_22_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_23_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_23_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_24_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_24_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_25_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_25_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_26_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_26_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_27_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_27_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_28_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_28_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_29_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_29_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_2_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_2_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_30_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_30_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_31_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_31_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_3_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_3_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_4_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_4_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_5_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_5_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_6_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_6_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_7_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_7_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_8_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_8_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln32_reg_1907_pp0_iter2_reg == 1'd1))) begin
        distance_buffer_9_3_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_9_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_in_a_ce0 = 1'b1;
    end else begin
        local_in_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_in_b_ce0 = 1'b1;
    end else begin
        local_in_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        local_in_c_ce0 = 1'b1;
    end else begin
        local_in_c_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_1035_p2 = (indvar_flatten_fu_246 + 37'd1);

assign add_ln33_fu_1058_p2 = (select_ln32_fu_1050_p3 + 6'd1);

assign add_ln35_fu_1077_p2 = (zext_ln27 + zext_ln35_fu_1074_p1);

assign add_ln36_fu_1087_p2 = (zext_ln36 + zext_ln35_fu_1074_p1);

assign add_ln37_fu_1097_p2 = (zext_ln37 + zext_ln35_fu_1074_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1000 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd2) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1003 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd3) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1006 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd4) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1009 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd5) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1012 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd6) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1015 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd7) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1018 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd1) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1021 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd8) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1024 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd9) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1027 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd10) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1030 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd11) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1033 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd12) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1036 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd13) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1039 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd14) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1042 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd15) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1045 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd16) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1048 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd17) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1051 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd18) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1054 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd19) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1057 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd20) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1060 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd21) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1063 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd22) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1066 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd23) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1069 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd24) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1072 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd25) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1075 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd26) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1078 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd27) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1081 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd28) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1084 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd29) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1087 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd30) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1090 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd31) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_condition_1093 = ((icmp_ln39_1_fu_1323_p2 == 1'd1) & (icmp_ln39_fu_1277_p2 == 1'd0) & (dst_reg_2091 == 5'd0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign distance_buffer_0_31_out = distance_buffer_1_fu_250;

assign distance_buffer_10_3_out = distance_buffer_1_42_fu_290;

assign distance_buffer_11_3_out = distance_buffer_1_43_fu_294;

assign distance_buffer_12_3_out = distance_buffer_1_44_fu_298;

assign distance_buffer_13_3_out = distance_buffer_1_45_fu_302;

assign distance_buffer_14_3_out = distance_buffer_1_46_fu_306;

assign distance_buffer_15_3_out = distance_buffer_1_47_fu_310;

assign distance_buffer_16_3_out = distance_buffer_1_48_fu_314;

assign distance_buffer_17_3_out = distance_buffer_1_49_fu_318;

assign distance_buffer_18_3_out = distance_buffer_1_50_fu_322;

assign distance_buffer_19_3_out = distance_buffer_1_51_fu_326;

assign distance_buffer_1_3_out = distance_buffer_1_3_fu_254;

assign distance_buffer_1_65_fu_1282_p2 = (weight_reg_2096 + tmp_reg_2101);

assign distance_buffer_20_3_out = distance_buffer_1_52_fu_330;

assign distance_buffer_21_3_out = distance_buffer_1_53_fu_334;

assign distance_buffer_22_3_out = distance_buffer_1_54_fu_338;

assign distance_buffer_23_3_out = distance_buffer_1_55_fu_342;

assign distance_buffer_24_3_out = distance_buffer_1_56_fu_346;

assign distance_buffer_25_3_out = distance_buffer_1_57_fu_350;

assign distance_buffer_26_3_out = distance_buffer_1_58_fu_354;

assign distance_buffer_27_3_out = distance_buffer_1_59_fu_358;

assign distance_buffer_28_3_out = distance_buffer_1_60_fu_362;

assign distance_buffer_29_3_out = distance_buffer_1_61_fu_366;

assign distance_buffer_2_3_out = distance_buffer_1_34_fu_258;

assign distance_buffer_30_3_out = distance_buffer_1_62_fu_370;

assign distance_buffer_31_3_out = distance_buffer_1_63_fu_374;

assign distance_buffer_3_3_out = distance_buffer_1_35_fu_262;

assign distance_buffer_4_3_out = distance_buffer_1_36_fu_266;

assign distance_buffer_5_3_out = distance_buffer_1_37_fu_270;

assign distance_buffer_6_3_out = distance_buffer_1_38_fu_274;

assign distance_buffer_7_3_out = distance_buffer_1_39_fu_278;

assign distance_buffer_8_3_out = distance_buffer_1_40_fu_282;

assign distance_buffer_9_3_out = distance_buffer_1_41_fu_286;

assign icmp_ln32_fu_1030_p2 = ((indvar_flatten_fu_246 == bound) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_1044_p2 = ((j_1_fu_242 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln39_1_fu_1323_p2 = ((distance_buffer_1_65_fu_1282_p2 < tmp_s_fu_1286_p34) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_1277_p2 = ((tmp_reg_2101 == 32'd4294967295) ? 1'b1 : 1'b0);

assign local_in_a_address0 = zext_ln35_2_fu_1082_p1;

assign local_in_b_address0 = zext_ln36_2_fu_1092_p1;

assign local_in_c_address0 = zext_ln37_2_fu_1102_p1;

assign select_ln32_fu_1050_p3 = ((icmp_ln33_fu_1044_p2[0:0] == 1'b1) ? 6'd0 : j_1_fu_242);

assign tmp_fu_1207_p33 = local_in_a_q0[4:0];

assign zext_ln35_2_fu_1082_p1 = add_ln35_fu_1077_p2;

assign zext_ln35_fu_1074_p1 = select_ln32_reg_1911;

assign zext_ln36_2_fu_1092_p1 = add_ln36_fu_1087_p2;

assign zext_ln37_2_fu_1102_p1 = add_ln37_fu_1097_p2;

endmodule //sssp_kernel_0_PE_kernel_1_Pipeline_sssp_computation_VITIS_LOOP_33_1
