// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sssp_kernel_0_PE_kernel_1_Pipeline_init_distances (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln27,
        local_in_a_address0,
        local_in_a_ce0,
        local_in_a_q0,
        distance_buffer_31_0_out,
        distance_buffer_31_0_out_ap_vld,
        distance_buffer_30_0_out,
        distance_buffer_30_0_out_ap_vld,
        distance_buffer_29_0_out,
        distance_buffer_29_0_out_ap_vld,
        distance_buffer_28_0_out,
        distance_buffer_28_0_out_ap_vld,
        distance_buffer_27_0_out,
        distance_buffer_27_0_out_ap_vld,
        distance_buffer_26_0_out,
        distance_buffer_26_0_out_ap_vld,
        distance_buffer_25_0_out,
        distance_buffer_25_0_out_ap_vld,
        distance_buffer_24_0_out,
        distance_buffer_24_0_out_ap_vld,
        distance_buffer_23_0_out,
        distance_buffer_23_0_out_ap_vld,
        distance_buffer_22_0_out,
        distance_buffer_22_0_out_ap_vld,
        distance_buffer_21_0_out,
        distance_buffer_21_0_out_ap_vld,
        distance_buffer_20_0_out,
        distance_buffer_20_0_out_ap_vld,
        distance_buffer_19_0_out,
        distance_buffer_19_0_out_ap_vld,
        distance_buffer_18_0_out,
        distance_buffer_18_0_out_ap_vld,
        distance_buffer_17_0_out,
        distance_buffer_17_0_out_ap_vld,
        distance_buffer_16_0_out,
        distance_buffer_16_0_out_ap_vld,
        distance_buffer_15_0_out,
        distance_buffer_15_0_out_ap_vld,
        distance_buffer_14_0_out,
        distance_buffer_14_0_out_ap_vld,
        distance_buffer_13_0_out,
        distance_buffer_13_0_out_ap_vld,
        distance_buffer_12_0_out,
        distance_buffer_12_0_out_ap_vld,
        distance_buffer_11_0_out,
        distance_buffer_11_0_out_ap_vld,
        distance_buffer_10_0_out,
        distance_buffer_10_0_out_ap_vld,
        distance_buffer_9_0_out,
        distance_buffer_9_0_out_ap_vld,
        distance_buffer_8_0_out,
        distance_buffer_8_0_out_ap_vld,
        distance_buffer_7_0_out,
        distance_buffer_7_0_out_ap_vld,
        distance_buffer_6_0_out,
        distance_buffer_6_0_out_ap_vld,
        distance_buffer_5_0_out,
        distance_buffer_5_0_out_ap_vld,
        distance_buffer_4_0_out,
        distance_buffer_4_0_out_ap_vld,
        distance_buffer_3_0_out,
        distance_buffer_3_0_out_ap_vld,
        distance_buffer_2_0_out,
        distance_buffer_2_0_out_ap_vld,
        distance_buffer_1_0_out,
        distance_buffer_1_0_out_ap_vld,
        distance_buffer_0_0_out,
        distance_buffer_0_0_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] zext_ln27;
output  [11:0] local_in_a_address0;
output   local_in_a_ce0;
input  [31:0] local_in_a_q0;
output  [31:0] distance_buffer_31_0_out;
output   distance_buffer_31_0_out_ap_vld;
output  [31:0] distance_buffer_30_0_out;
output   distance_buffer_30_0_out_ap_vld;
output  [31:0] distance_buffer_29_0_out;
output   distance_buffer_29_0_out_ap_vld;
output  [31:0] distance_buffer_28_0_out;
output   distance_buffer_28_0_out_ap_vld;
output  [31:0] distance_buffer_27_0_out;
output   distance_buffer_27_0_out_ap_vld;
output  [31:0] distance_buffer_26_0_out;
output   distance_buffer_26_0_out_ap_vld;
output  [31:0] distance_buffer_25_0_out;
output   distance_buffer_25_0_out_ap_vld;
output  [31:0] distance_buffer_24_0_out;
output   distance_buffer_24_0_out_ap_vld;
output  [31:0] distance_buffer_23_0_out;
output   distance_buffer_23_0_out_ap_vld;
output  [31:0] distance_buffer_22_0_out;
output   distance_buffer_22_0_out_ap_vld;
output  [31:0] distance_buffer_21_0_out;
output   distance_buffer_21_0_out_ap_vld;
output  [31:0] distance_buffer_20_0_out;
output   distance_buffer_20_0_out_ap_vld;
output  [31:0] distance_buffer_19_0_out;
output   distance_buffer_19_0_out_ap_vld;
output  [31:0] distance_buffer_18_0_out;
output   distance_buffer_18_0_out_ap_vld;
output  [31:0] distance_buffer_17_0_out;
output   distance_buffer_17_0_out_ap_vld;
output  [31:0] distance_buffer_16_0_out;
output   distance_buffer_16_0_out_ap_vld;
output  [31:0] distance_buffer_15_0_out;
output   distance_buffer_15_0_out_ap_vld;
output  [31:0] distance_buffer_14_0_out;
output   distance_buffer_14_0_out_ap_vld;
output  [31:0] distance_buffer_13_0_out;
output   distance_buffer_13_0_out_ap_vld;
output  [31:0] distance_buffer_12_0_out;
output   distance_buffer_12_0_out_ap_vld;
output  [31:0] distance_buffer_11_0_out;
output   distance_buffer_11_0_out_ap_vld;
output  [31:0] distance_buffer_10_0_out;
output   distance_buffer_10_0_out_ap_vld;
output  [31:0] distance_buffer_9_0_out;
output   distance_buffer_9_0_out_ap_vld;
output  [31:0] distance_buffer_8_0_out;
output   distance_buffer_8_0_out_ap_vld;
output  [31:0] distance_buffer_7_0_out;
output   distance_buffer_7_0_out_ap_vld;
output  [31:0] distance_buffer_6_0_out;
output   distance_buffer_6_0_out_ap_vld;
output  [31:0] distance_buffer_5_0_out;
output   distance_buffer_5_0_out_ap_vld;
output  [31:0] distance_buffer_4_0_out;
output   distance_buffer_4_0_out_ap_vld;
output  [31:0] distance_buffer_3_0_out;
output   distance_buffer_3_0_out_ap_vld;
output  [31:0] distance_buffer_2_0_out;
output   distance_buffer_2_0_out_ap_vld;
output  [31:0] distance_buffer_1_0_out;
output   distance_buffer_1_0_out_ap_vld;
output  [31:0] distance_buffer_0_0_out;
output   distance_buffer_0_0_out_ap_vld;

reg ap_idle;
reg local_in_a_ce0;
reg distance_buffer_31_0_out_ap_vld;
reg distance_buffer_30_0_out_ap_vld;
reg distance_buffer_29_0_out_ap_vld;
reg distance_buffer_28_0_out_ap_vld;
reg distance_buffer_27_0_out_ap_vld;
reg distance_buffer_26_0_out_ap_vld;
reg distance_buffer_25_0_out_ap_vld;
reg distance_buffer_24_0_out_ap_vld;
reg distance_buffer_23_0_out_ap_vld;
reg distance_buffer_22_0_out_ap_vld;
reg distance_buffer_21_0_out_ap_vld;
reg distance_buffer_20_0_out_ap_vld;
reg distance_buffer_19_0_out_ap_vld;
reg distance_buffer_18_0_out_ap_vld;
reg distance_buffer_17_0_out_ap_vld;
reg distance_buffer_16_0_out_ap_vld;
reg distance_buffer_15_0_out_ap_vld;
reg distance_buffer_14_0_out_ap_vld;
reg distance_buffer_13_0_out_ap_vld;
reg distance_buffer_12_0_out_ap_vld;
reg distance_buffer_11_0_out_ap_vld;
reg distance_buffer_10_0_out_ap_vld;
reg distance_buffer_9_0_out_ap_vld;
reg distance_buffer_8_0_out_ap_vld;
reg distance_buffer_7_0_out_ap_vld;
reg distance_buffer_6_0_out_ap_vld;
reg distance_buffer_5_0_out_ap_vld;
reg distance_buffer_4_0_out_ap_vld;
reg distance_buffer_3_0_out_ap_vld;
reg distance_buffer_2_0_out_ap_vld;
reg distance_buffer_1_0_out_ap_vld;
reg distance_buffer_0_0_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln25_fu_543_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln25_reg_1079;
wire   [4:0] trunc_ln27_fu_570_p1;
reg   [4:0] trunc_ln27_reg_1088;
reg   [4:0] trunc_ln27_reg_1088_pp0_iter1_reg;
reg   [31:0] local_in_a_load_reg_1092;
wire   [63:0] zext_ln27_4_fu_565_p1;
wire    ap_block_pp0_stage0;
reg   [5:0] j_fu_160;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_3;
wire   [5:0] add_ln25_fu_549_p2;
reg   [31:0] distance_buffer_0_0_fu_164;
wire   [31:0] select_ln27_fu_584_p3;
reg   [31:0] distance_buffer_1_0_fu_168;
reg   [31:0] distance_buffer_2_0_fu_172;
reg   [31:0] distance_buffer_3_0_fu_176;
reg   [31:0] distance_buffer_4_0_fu_180;
reg   [31:0] distance_buffer_5_0_fu_184;
reg   [31:0] distance_buffer_6_0_fu_188;
reg   [31:0] distance_buffer_7_0_fu_192;
reg   [31:0] distance_buffer_8_0_fu_196;
reg   [31:0] distance_buffer_9_0_fu_200;
reg   [31:0] distance_buffer_10_0_fu_204;
reg   [31:0] distance_buffer_11_0_fu_208;
reg   [31:0] distance_buffer_12_0_fu_212;
reg   [31:0] distance_buffer_13_0_fu_216;
reg   [31:0] distance_buffer_14_0_fu_220;
reg   [31:0] distance_buffer_15_0_fu_224;
reg   [31:0] distance_buffer_16_0_fu_228;
reg   [31:0] distance_buffer_17_0_fu_232;
reg   [31:0] distance_buffer_18_0_fu_236;
reg   [31:0] distance_buffer_19_0_fu_240;
reg   [31:0] distance_buffer_20_0_fu_244;
reg   [31:0] distance_buffer_21_0_fu_248;
reg   [31:0] distance_buffer_22_0_fu_252;
reg   [31:0] distance_buffer_23_0_fu_256;
reg   [31:0] distance_buffer_24_0_fu_260;
reg   [31:0] distance_buffer_25_0_fu_264;
reg   [31:0] distance_buffer_26_0_fu_268;
reg   [31:0] distance_buffer_27_0_fu_272;
reg   [31:0] distance_buffer_28_0_fu_276;
reg   [31:0] distance_buffer_29_0_fu_280;
reg   [31:0] distance_buffer_30_0_fu_284;
reg   [31:0] distance_buffer_31_0_fu_288;
wire    ap_block_pp0_stage0_01001;
wire   [11:0] zext_ln27_3_fu_555_p1;
wire   [11:0] add_ln27_fu_559_p2;
wire   [0:0] distance_buffer_1_fu_579_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

sssp_kernel_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln25_fu_543_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_160 <= add_ln25_fu_549_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_160 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln25_reg_1079 <= icmp_ln25_fu_543_p2;
        local_in_a_load_reg_1092 <= local_in_a_q0;
        trunc_ln27_reg_1088_pp0_iter1_reg <= trunc_ln27_reg_1088;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd0))) begin
        distance_buffer_0_0_fu_164 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd10))) begin
        distance_buffer_10_0_fu_204 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd11))) begin
        distance_buffer_11_0_fu_208 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd12))) begin
        distance_buffer_12_0_fu_212 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd13))) begin
        distance_buffer_13_0_fu_216 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd14))) begin
        distance_buffer_14_0_fu_220 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd15))) begin
        distance_buffer_15_0_fu_224 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd16))) begin
        distance_buffer_16_0_fu_228 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd17))) begin
        distance_buffer_17_0_fu_232 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd18))) begin
        distance_buffer_18_0_fu_236 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd19))) begin
        distance_buffer_19_0_fu_240 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd1))) begin
        distance_buffer_1_0_fu_168 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd20))) begin
        distance_buffer_20_0_fu_244 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd21))) begin
        distance_buffer_21_0_fu_248 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd22))) begin
        distance_buffer_22_0_fu_252 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd23))) begin
        distance_buffer_23_0_fu_256 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd24))) begin
        distance_buffer_24_0_fu_260 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd25))) begin
        distance_buffer_25_0_fu_264 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd26))) begin
        distance_buffer_26_0_fu_268 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd27))) begin
        distance_buffer_27_0_fu_272 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd28))) begin
        distance_buffer_28_0_fu_276 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd29))) begin
        distance_buffer_29_0_fu_280 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd2))) begin
        distance_buffer_2_0_fu_172 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd30))) begin
        distance_buffer_30_0_fu_284 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd31))) begin
        distance_buffer_31_0_fu_288 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd3))) begin
        distance_buffer_3_0_fu_176 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd4))) begin
        distance_buffer_4_0_fu_180 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd5))) begin
        distance_buffer_5_0_fu_184 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd6))) begin
        distance_buffer_6_0_fu_188 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd7))) begin
        distance_buffer_7_0_fu_192 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd8))) begin
        distance_buffer_8_0_fu_196 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln27_reg_1088_pp0_iter1_reg == 5'd9))) begin
        distance_buffer_9_0_fu_200 <= select_ln27_fu_584_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_fu_543_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln27_reg_1088 <= trunc_ln27_fu_570_p1;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_543_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_3 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_0_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_0_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_10_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_10_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_11_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_11_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_12_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_12_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_13_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_13_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_14_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_14_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_15_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_15_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_16_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_16_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_17_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_17_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_18_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_18_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_19_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_19_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_1_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_1_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_20_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_20_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_21_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_21_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_22_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_22_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_23_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_23_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_24_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_24_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_25_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_25_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_26_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_26_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_27_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_27_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_28_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_28_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_29_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_29_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_2_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_2_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_30_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_30_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_31_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_31_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_3_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_3_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_4_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_4_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_5_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_5_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_6_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_6_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_7_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_7_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_8_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_8_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_1079 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        distance_buffer_9_0_out_ap_vld = 1'b1;
    end else begin
        distance_buffer_9_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_a_ce0 = 1'b1;
    end else begin
        local_in_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_fu_549_p2 = (ap_sig_allocacmp_j_3 + 6'd1);

assign add_ln27_fu_559_p2 = (zext_ln27 + zext_ln27_3_fu_555_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign distance_buffer_0_0_out = distance_buffer_0_0_fu_164;

assign distance_buffer_10_0_out = distance_buffer_10_0_fu_204;

assign distance_buffer_11_0_out = distance_buffer_11_0_fu_208;

assign distance_buffer_12_0_out = distance_buffer_12_0_fu_212;

assign distance_buffer_13_0_out = distance_buffer_13_0_fu_216;

assign distance_buffer_14_0_out = distance_buffer_14_0_fu_220;

assign distance_buffer_15_0_out = distance_buffer_15_0_fu_224;

assign distance_buffer_16_0_out = distance_buffer_16_0_fu_228;

assign distance_buffer_17_0_out = distance_buffer_17_0_fu_232;

assign distance_buffer_18_0_out = distance_buffer_18_0_fu_236;

assign distance_buffer_19_0_out = distance_buffer_19_0_fu_240;

assign distance_buffer_1_0_out = distance_buffer_1_0_fu_168;

assign distance_buffer_1_fu_579_p2 = ((local_in_a_load_reg_1092 != 32'd0) ? 1'b1 : 1'b0);

assign distance_buffer_20_0_out = distance_buffer_20_0_fu_244;

assign distance_buffer_21_0_out = distance_buffer_21_0_fu_248;

assign distance_buffer_22_0_out = distance_buffer_22_0_fu_252;

assign distance_buffer_23_0_out = distance_buffer_23_0_fu_256;

assign distance_buffer_24_0_out = distance_buffer_24_0_fu_260;

assign distance_buffer_25_0_out = distance_buffer_25_0_fu_264;

assign distance_buffer_26_0_out = distance_buffer_26_0_fu_268;

assign distance_buffer_27_0_out = distance_buffer_27_0_fu_272;

assign distance_buffer_28_0_out = distance_buffer_28_0_fu_276;

assign distance_buffer_29_0_out = distance_buffer_29_0_fu_280;

assign distance_buffer_2_0_out = distance_buffer_2_0_fu_172;

assign distance_buffer_30_0_out = distance_buffer_30_0_fu_284;

assign distance_buffer_31_0_out = distance_buffer_31_0_fu_288;

assign distance_buffer_3_0_out = distance_buffer_3_0_fu_176;

assign distance_buffer_4_0_out = distance_buffer_4_0_fu_180;

assign distance_buffer_5_0_out = distance_buffer_5_0_fu_184;

assign distance_buffer_6_0_out = distance_buffer_6_0_fu_188;

assign distance_buffer_7_0_out = distance_buffer_7_0_fu_192;

assign distance_buffer_8_0_out = distance_buffer_8_0_fu_196;

assign distance_buffer_9_0_out = distance_buffer_9_0_fu_200;

assign icmp_ln25_fu_543_p2 = ((ap_sig_allocacmp_j_3 == 6'd32) ? 1'b1 : 1'b0);

assign local_in_a_address0 = zext_ln27_4_fu_565_p1;

assign select_ln27_fu_584_p3 = ((distance_buffer_1_fu_579_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign trunc_ln27_fu_570_p1 = ap_sig_allocacmp_j_3[4:0];

assign zext_ln27_3_fu_555_p1 = ap_sig_allocacmp_j_3;

assign zext_ln27_4_fu_565_p1 = add_ln27_fu_559_p2;

endmodule //sssp_kernel_0_PE_kernel_1_Pipeline_init_distances
